version: "2"
services: 
  api:
    image: hoangnam1301/data-processing-service
    build: .
    environment:
      DEBUG: 1
      PYTHONDONTWRITEBYTECODE: 1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8008 --reload
    volumes:
      - ./app:/code/app
    ports:
      - 8018:8008
    env_file:
      ./.env
    networks:
      - network_test
networks:
 network_test:
   external: true
